version: '3'

services:
  nginx:
    image: nginx
    container_name: proxy
    networks:
      - reverse_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - node

  node:
    build:
      context: ./node
    image: jonathananthony/node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: npm run dev
    networks:
      - reverse_proxy
    volumes:
      - ./node:/app
    depends_on:
      - db
  
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    driver: bridge